plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ammambouy.steelfrontier'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ammambouy.steelfrontier'
        minSdk 23
        targetSdk 35
        versionCode 147
        versionName '1.4.7'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
