plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ammambouy.steelfrontier'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ammambouy.steelfrontier'
        minSdk 23
        targetSdk 35
        versionCode 150
        versionName '1.5.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.7'
}
